### ISSUE TITLE
Build MatterLink as a Spigot/Bukkit plugin

### ISSUE THREAD

**Issue by Programie** [elytra/MatterLink#15]
Currently, MatterLink is a mod for Forge. But would it be possible to extend it to also support building it as a plugin for Spigot/Bukkit?

Spigot [supports](https://www.spigotmc.org/wiki/how-to-use-kotlin-in-your-plugins/) plugins written in Kotlin, so I guess it should be easy to add the correct event handlers. But I don't know how to setup a project which supports Forge and Spigot/Bukkit from the same code base.

I have some knowledge in writing plugins using the Bukkit API, but I have no knowledge of Kotlin at all.

**Comment by NikkyAI** [comment]
feel free to fork and grab the relevant code, i am available on discord and irc if there are more things to discuss
it might be really easy, but currently its structured this way because things across minecraft versions do nto really change on forge

**Comment by Wurmatron** [comment]
If you just need MatterBridge Support its quite easy to port to Bukkit.  Between Nikky's code along with mine (in java), it should be easy to port.  [MatterLink SE Module](https://github.com/Wurmcraft/Server-Essentials/blob/Post-Rest-Rework/src/main/java/com/wurmcraft/serveressentials/common/modules/matterbridge/MatterBridgeModule.java)

**Comment by Programie** [comment]
A few days ago, I started to write a Bukkit plugin with basic integration of MatterBridge (i.e. chat relay, advancement announcements to MatterBridge, etc.) but no advanced stuff like commands, formatting, etc.: https://github.com/Programie/MatterBukkit

I don't know whether it's better to have a different plugin for Bukkit or just extend MatterLink to also support Bukkit. Using the same plugin would have the advantage of reusing the code.

**Comment by NikkyAI** [comment]
i am not maintaining matterlink past this and simple bugfixes, so a fork and a different codebase for bukkit seems fine

**Comment by Programie** [comment]
So, I guess we can close this issue, right?
