### ISSUE TITLE
ConventionalChat support

### ISSUE THREAD

**Issue by Ristellise** [elytra/MatterLink#6]
Should support:
- [x] Nicknames
- [x] color codes

**Comment by Ristellise** [comment]
and colour codes

**Comment by NikkyAI** [comment]
nicknames are implemented in 1.5.4 / f367690789924d3c0b96a5092b5e01641e37c169

**Comment by NikkyAI** [comment]
how would you like to handle color codes ? filter them all out or have them partially filtered / converted ?

**Comment by Ristellise** [comment]
filter them all out

**Comment by NikkyAI** [comment]
color code stripping was added in 68144ae51232e25104ea4703aefb8f2ad3401dda
and the latest version on jenkins has the next feature to play with
