### ISSUE TITLE
Not getting the /config command

### ISSUE THREAD

**Issue by jasperfirecai2** [elytra/MatterLink#7]
i installed the lastest release for 1.12 on a sevtech: ages server and the /config command does not show up. 
I'm having other issues too, but i'm pretty sure those are my-side right now.

**Comment by NikkyAI** [comment]
there is no config command.. you can edit the config and call `/bridge reload`
also make sure you are running a matterbridge

**Comment by NikkyAI** [comment]
if you are up to hopping on discord or irc i can help with the setup directly if any issues arise (the matterbridge configuration is sadly not entirely simple)

**Comment by NikkyAI** [comment]
and yes that was a bad typo on the project description.. i have really not maintained that properly.. my bad

**Comment by jasperfirecai2** [comment]
That would be awesome if you could! my discord tag is Toxic Velkoz meme aka Jasper#1440

**Comment by NikkyAI** [comment]
are you sure that was not typoed.. i seem to be unable to add you, maybe try me i am in the MMD disocrd and others 
my name and tag is Nikky#4527

**Comment by jasperfirecai2** [comment]
http://puu.sh/ArEX6/bf61dba780.png

**Comment by NikkyAI** [comment]
gah

**Comment by jasperfirecai2** [comment]
i've sent it now
