### ISSUE TITLE
Log "spam", user disconnected

### ISSUE THREAD

**Issue by Wurmatron** [elytra/MatterLink#9]
http://prntscr.com/k19idg

This is not anything important but if a user keeps relogging it will start to spam console. I suggest only printing this message if its used and not empty.

https://github.com/elytra/MatterLink/blob/master/core/src/main/kotlin/matterlink/handlers/JoinLeaveHandler.kt#L20

**Comment by NikkyAI** [comment]
must have forgot a logger call from debugging in there... 
fixed in 66229f4308615c358cb1e8055e9212fbd9b64ee8
moved that message to DEBUG loglevel and made sure it has a toString
